### ISSUE TITLE
Meet 01

### ISSUE THREAD

**Issue by dogecade** [4Mens4Coding/MathOCRLibrary#1]
Dalykai kuriuos reikia nuspręst:

- [  ]  Koks coding style 

Tarpas po funkcijos 
if/for/while su skliausteliais 
tarp kintamuju tarpai; pvz. int a, b, c
aplink operatorius tarpai
Komentarais pasirasom kas parase funkcija
Tikslus importai; pvz. import milziniskas_libas.butent_sitas_algoritmas
Funkcijos is mazosios
Klases is didziosios
JeiPavadinimeDaugZodziuJuosRasomTaip
rinkiniai a = [], o ne a = [ ]
a[], o ne a[ 1 ]
du enteriai po funkcijos

- [  ]  +/- kokiais stepsais suskaldom kūrimą

Reikia testines datos dafiga ko daugiau tuo geriau:
reikia skaiciu nuo 0 - 9 
reikia + - =

Paversti image i binarini kazkokia data (image binarization)

Reikia patikrint machine learningo algoritmus kurie labiausiai tinka 

Per excel visus raidziu pavyzdzius padaryt su scriptu ir konvertuot i PDF (Siūlymas)

- [  ]  Nuo ko pradedam ? Ar visi bandom tą patį pradžioj krapštyt? Ar bandom skirtingus?

**Comment by dogecade** [comment]
@valentk777 @DeividasBrazenas @tomas-drasutis dv xebryte tokius klausimus ir bandom pakrapštyt šian. Ar turit papildimų?

**Comment by tomas-drasutis** [comment]
Manau, kad šitie geri

**Comment by DeividasBrazenas** [comment]
Dar gali but, su kokiom problemom galim susidurt early stepsuose OCR rasymo

**Comment by valentk777** [comment]
man tinka kl. pakuriau Projekta. ten galesim det atskirus issue ar siaip dalykus
ten galesim priskirt zmones ir panasiai. ka manot?

**Comment by valentk777** [comment]
galesim ta project naudot kaip stepsus musu projekto pletroje. nu tipo. padaryt veikianti OCR, padaryt veikianti konvertavima i latex, implementuoti veikima su worfr... ir pan
